apiVersion: batch/v1
kind: Job
metadata:
  name: loadtest
spec:
  template:
    spec:
      containers:
      - name: siege
        image: schoolofdevops/loadtest:v1
        command: ["siege",  "--concurrent=20", "--benchmark", "--time=10m", "http://php-apache"]
      restartPolicy: Never
  backoffLimit: 4